Add page1150.txt
PDP-6/ITS pull request #19
Opened 2023-11-24 00:46 UTC by sebras

2023-11-24 08:18 UTC, larsbrinkhoff requested changes

2023-11-24 08:18 UTC, larsbrinkhoff commented on transcribed/page1150.txt
> +003
Missing label.

2023-11-24 08:18 UTC, larsbrinkhoff commented on transcribed/page1150.txt
> +012     105 003         MOVE MC,UTP1
MOVEM C

2023-11-25 05:18 UTC, merged

2023-11-26 11:45 UTC, sebras commented on transcribed/page1150.txt
> +003
`JDB3B:` yeah, I missed that.