Add page1180.txt
PDP-6/ITS pull request #22
Opened 2023-11-24 00:47 UTC by sebras

2023-11-24 08:53 UTC, larsbrinkhoff requested changes

2023-11-24 08:53 UTC, larsbrinkhoff commented on transcribed/page1180.txt
> +024             UPR:    0       ;USER PROTECTIONA AND RELOCATION REGISTERS
PROTECTION

2023-11-24 08:53 UTC, larsbrinkhoff commented on transcribed/page1180.txt
> +038             ; STATES=> 0 => RUNABLE
STATES =>

2023-11-25 05:33 UTC, merged

2023-11-26 11:34 UTC, sebras commented on transcribed/page1180.txt
> +024             UPR:    0       ;USER PROTECTIONA AND RELOCATION REGISTERS
Yes.

2023-11-26 11:34 UTC, sebras commented on transcribed/page1180.txt
> +038             ; STATES=> 0 => RUNABLE
Yup.